# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "smylee"
license = "MIT"
licenselink = "https://github.com/smyleeface/smylee_hugo_site/theme/smylee/LICENSE.md"
description = ""
homepage = "http://smylee.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "Patricia Ramert"
  homepage = "http://smylee.com"

