version: 0.2

#env:
#  variables:
#    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
#  parameter-store:
#    LOGIN_PASSWORD: "dockerLoginPassword"

phases:
  build:
    commands:
      - echo Entered the install phase...
      - go get github.com/kardianos/govendor
      - govendor get github.com/gohugoio/hugo
      - go install github.com/gohugoio/hugo
      - cd ${CODEBUILD_SRC_DIR}/themes
      - git clone https://github.com/smyleeface/hugo_theme_beg.git beg
      - cd ${CODEBUILD_SRC_DIR}
      - hugo --theme beg
      - ls -la ${CODEBUILD_SRC_DIR}/public
#      - curl -L -o ./tmp/master.zip https://github.com/smyleeface/smylee_hugo_site/archive/master.zip
#      - unzip -o ./tmp/master.zip -d ./tmp/site
#      - ./tmp/site/hugo --theme=bug --source=./tmp/site
#  post_build:
#    commands:
#      - echo Entered the post_build phase...
#      - echo Build completed on `date`
artifacts:
  files:
    - ${CODEBUILD_SRC_DIR}/public/**/*
  discard-paths: yes
