version: 0.2
phases:
  build:
    commands:
      - echo "*** DOWNLOAD THEME"
      - git clone https://github.com/smyleeface/hugo_theme_beg.git themes/beg
      - echo "*** BUILD STAGING"
      - hugo --theme beg --baseURL https://staging.smylee.com/
      - ls -la ${CODEBUILD_SRC_DIR}
      - pwd
  post_build:
    commands:
      - echo "*** EMPTY S3 STAGING BUCKET"
      - aws s3 rm s3://staging.smylee.com --recursive

      # publishes to: https://s3-us-west-2.amazonaws.com/staging.smylee.com/CodeBuildArtifacts/*
      - echo "*** PUBLISHING TO S3 STAGING BUCKET"
      - aws s3 cp ${CODEBUILD_SRC_DIR}/public s3://staging.smylee.com --recursive
      - aws cloudfront create-invalidation --distribution-id E3U437VILY93UD --paths /

# For conditional builds
#      # copy all file except `index.html`
#      - aws s3 cp ${CODEBUILD_SRC_DIR}/public s3://staging.smylee.com --recursive --exclude index.html
#
#      # copy only `index.html` file and add extra metadata for caching
#      - aws s3 cp ${CODEBUILD_SRC_DIR}/public s3://staging.smylee.com --recursive --exclude "*" --include index.html --cache-control max-age=0

#NOTE: Cannot use the `artifacts` section
# it works ok, in CodeBuild
# but is ignored when CodeBuild is used in CodePipeline
# https://stackoverflow.com/questions/43131439/aws-codepipeline-adding-artifacts-to-s3-in-less-useful-format-than-running-steps
# https://docs.aws.amazon.com/codepipeline/latest/userguide/tutorials-simple-s3.html#s3-add-stage-part-2-console
#artifacts:
#  files:
#    - '**/*'
#  base-directory: ${CODEBUILD_SRC_DIR}/public
