version: 0.2
phases:
  build:
    commands:
      - echo "*** DOWNLOAD THEME"
      - git clone https://github.com/smyleeface/hugo_theme_beg.git themes/beg
      - echo "*** BUILD STAGING"
      - hugo --theme beg --baseURL http://staging.smylee.com/
      - ls -la ${CODEBUILD_SRC_DIR}/public
  post_build:
    commands:
      - echo "*** EMPTY S3 STAGING BUCKET"
      - aws s3 rm s3://staging.smylee.com --recursive

# publishes to: https://s3-us-west-2.amazonaws.com/staging.smylee.com/CodeBuildArtifacts/*
artifacts:
  files:
    - '**/*'
  base-directory: ${CODEBUILD_SRC_DIR}/public
