version: 0.2
phases:
  post_build:
    commands:
      - echo Entered the post_build phase...
      # TODO: check that staging has data before deleting
      - echo empty smylee.com...
      - aws s3 rm s3://smylee.com --exclude "images/**/*" --recursive
      - echo move smylee.com ...
      - aws s3 mv s3://staging.smylee.com/ s3://smylee.com/ --storage-class STANDARD --recursive
