version: 0.2
phases:
  install:
    commands:
      # https://gohugo.io/getting-started/installing/#source
      - echo Entered the install phase...
      - go get -u github.com/aws/aws-sdk-go/...
      - aws help
#      - echo Installing govendor...
#      - go get github.com/kardianos/govendor
#      - echo Installing hugo...
#      - govendor get github.com/gohugoio/hugo
#      - go install github.com/gohugoio/hugo
#  pre_build:
#    commands:
#      - echo Entered the pre_build phase...
#      - echo Installing theme...
#      - cd ${CODEBUILD_SRC_DIR}/themes
#      - git clone https://github.com/smyleeface/hugo_theme_beg.git beg
#  build:
#    commands:
#      - echo Entered the build phase...
#      - echo Run hugo...
#      - cd ${CODEBUILD_SRC_DIR}
#      - hugo --theme beg
#  post_build:
#    commands:
#      - echo Entered the post_build phase...
#      - cd ${CODEBUILD_SRC_DIR}/public
