baseurl = "http://smylee.com/"
languageCode = "en-us"
title = "smylee.com"
enableRobotsTXT = true
enableEmoji = true
googleAnalytics = "UA-80166115-1"

[Params]
  Author = "Patty R"
  DefaultImage = "http://cdn.smylee.com/static/default.png"
  LogoImage = "http://cdn.smylee.com/static/logo.png"
  CdnBaseUrl = "http://cdn.smylee.com/"

[taxonomies]
	tag = "tags"
	category = "categories"
