baseurl = "http://smylee.com/"
languageCode = "en-us"
title = "smylee.com"
enableRobotsTXT = true

[Params]
  Author = "Patty R"
  ImageCdnUrl = "http://cdn.smylee.com/"
  DefaultImage = "static/default.png"
  LogoImage = "static/logo.png"

[taxonomies]
	tag = "Tags"
	category = "Categories"
