languageCode = "en-us"
title = "smylee.com"
enableRobotsTXT = true
enableEmoji = true
googleAnalytics = "UA-80166115-1"

[Params]
  Author = "Patty R"
  DefaultImage = "https://cdn.smylee.com/static/default.png"
  LogoImage = "https://cdn.smylee.com/static/logo.png"
  CdnBaseUrl = "https://cdn.smylee.com/"

[taxonomies]
	tag = "tags"
	category = "categories"
