languageCode = "en-us"
title = "smylee.com"
enableRobotsTXT = true
enableEmoji = true
googleAnalytics = "UA-80166115-1"

[Params]
  Author = "Patty R"
  DefaultImage = "images/static/default.png"
  LogoImage = "images/static/logo.png"

[taxonomies]
	tag = "tags"
	category = "categories"
